# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [6]:
#your code here
from itertools import combinations, cycle, islice
answer = combinations(['A', 'B', 'C'], 2)
for ans in answer:
    print(ans)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [10]:
#your code here
cycle_answer = cycle(['Python', 'is', 'fun'])
answer = list(islice(cycle_answer, 10))
for ans in answer:
    print(ans)

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [12]:
#your code here
import glob

python_files = glob.glob("*.py")

for file in python_files:
    print(file)

bro.py


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [17]:
# <html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [16]:
#your code here
from bs4 import BeautifulSoup
doc = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
soup = BeautifulSoup(doc, 'html.parser')

def extractText():

    for paragraph in soup.find_all('p'):
        print(paragraph.string)

extractText()

AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [18]:
#your code here
import re


def replacer(text):
    return re.sub(r'AI', 'Artificial Intelligence', text)

replacer()

Artificial Intelligence will replace us. Be careful about Artificial Intelligence


**CP6**: Create a numpy array of 10 zeros.

In [20]:
#your code here
import numpy as np

arr = np.zeros(10, dtype=int)

[0 0 0 0 0 0 0 0 0 0]


**CP7** Create a numpy array of the integers from 10 to 49.

In [21]:
#your code here
arr = np.arange(10, 50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [22]:
#your code here
arr = np.arange(0, 9).reshape((3, 3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [ ]:
# Machine learning models require large amount of data because 
# it will give them a better chance of figuring out general patterns inside
# the dataset. If the data isn't large, that would mean the model
# will be limited in figuring out the pattern that exist in the overlying 
# large dataset. This would lead in making the model memorize details of 
# the data instead of learning the underlying pattern which is usually 
# the most important thing for it to learn. By large amount of data
# it is usually meant a data that's representative of the wider observation.
# The largeness signifies the huge sample of data that would aid in making 
# the model make accurate prediction on data it hasn't encountered before.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [ ]:
# 1. Generating fake content or media: AI can be used to create real-looking but
# false content such as pictures or videos. This can be prevented by putting in 
# more research on how AI models can detect the fake ones form the real ones.
# 2. Replacing jobs that can be done by AI: Since AI is only going to get smarter
# it will be more likely that it would replace jobs that can be automated. This would 
# mean increased unemployement but it can be countered by upskilling individuals
# in AI development to get opportunities AI will provide.